name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'
  repository_dispatch:
    types: [ version-changed ]
  workflow_dispatch:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fonts: [true, false]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load Version
        run: |
          TWITCHDOWNLOADER_VERSION=$(head -n 1 .versions/twitchdownloader)
          FONTS_VERSION=$(head -n 1 .versions/fonts)
          SHORT_FONTS_VERSION="${FONTS_VERSION:0:7}"
          echo "TWITCHDOWNLOADER_VERSION=$TWITCHDOWNLOADER_VERSION" >> $GITHUB_ENV
          echo "SHORT_FONTS_VERSION=$SHORT_FONTS_VERSION" >> $GITHUB_ENV

      - name: Set tags based on matrix value
        id: set-tags
        run: |
          if [[ "${{ matrix.fonts }}" == "true" ]]; then
            echo "LATEST_TAG=latest" >> $GITHUB_ENV
            echo "VERSION_TAG=${{ env.TWITCHDOWNLOADER_VERSION }}" >> $GITHUB_ENV
            echo "VERSION2_TAG=${{ env.TWITCHDOWNLOADER_VERSION }}-${{ env.SHORT_FONTS_VERSION }}" >> $GITHUB_ENV
          else
            echo "LATEST_TAG=latest-nofonts" >> $GITHUB_ENV
            echo "VERSION_TAG=${{ env.TWITCHDOWNLOADER_VERSION }}-nofonts" >> $GITHUB_ENV
            echo "VERSION2_TAG=${{ env.TWITCHDOWNLOADER_VERSION }}-nofonts" >> $GITHUB_ENV
          fi
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            bedlaj/twitchdownloader:${{ env.LATEST_TAG }}
            bedlaj/twitchdownloader:${{ env.VERSION_TAG }}
            bedlaj/twitchdownloader:${{ env.VERSION2_TAG }}
          build-args: |
            TWITCHDOWNLOADER_VERSION=${{ env.TWITCHDOWNLOADER_VERSION }}
            FONTS=${{ matrix.fonts }}
