name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'
  repository_dispatch:
    types: [ version-changed ]
  workflow_dispatch:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fonts: [true, false]
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Load Version
        run: |
          TWITCHDOWNLOADER_VERSION=$(cat .version)
          echo "TWITCHDOWNLOADER_VERSION=$TWITCHDOWNLOADER_VERSION" >> $GITHUB_ENV

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            bedlaj/twitchdownloader:${{ matrix.fonts && 'latest' || 'latest-nofonts' }}
            bedlaj/twitchdownloader:${{ env.TWITCHDOWNLOADER_VERSION }}${{ matrix.fonts && '' || '-nofonts' }}
          build-args: |
            TWITCHDOWNLOADER_VERSION=${{ env.TWITCHDOWNLOADER_VERSION }}
            FONTS=${{ matrix.fonts }}
