name: Check GoogleFonts commits

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-version-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Latest commit from GoogleFonts
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/google/fonts/commits/main | jq -r ".sha")
          echo "Latest version: $LATEST_VERSION"
          echo "$LATEST_VERSION" > .versions/fonts

      - name: Commit and Push
        id: commit_and_push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .versions/fonts
          COMMIT_MSG="Update GoogleFonts to $(cat .versions/fonts)"
          git commit -m "$COMMIT_MSG" && echo "version_changed=true" >> $GITHUB_ENV && git push origin HEAD:main || echo "version_changed=false" >> $GITHUB_ENV

      - name: Trigger Next Workflow
        if: env.version_changed == 'true'
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/dispatches" \
          -d '{"event_type": "workflow_dispatch"}'
